package com.mir.fitnessapplication.main.ui.fitness.exercises.inside

class InsideExerciseData() {
    val mutableList = mutableListOf(
        mutableListOf(
            InsideExerciseItemStorage("Подъемы штанги стоя","0oj5pY3RQrc", "10 - 12", "3 - 4"),
            InsideExerciseItemStorage("Подъемы гантелей стоя","UUdKpGSQgmc", "15 - 17", "3 - 4"),
            InsideExerciseItemStorage("Подъемы гантелей сидя","P957YHBOs6Q", "15 - 17", "3 - 4"),
            InsideExerciseItemStorage("Подъемы на скамье Скотта 1","xtFsz7zsM2U", "12 - 15", "3 - 4"),
            InsideExerciseItemStorage("Подъемы на скамье Скотта 2","xtFsz7zsM2U", "12 - 15", "3 - 4"),
            InsideExerciseItemStorage("Подтягивания узким обратным хватом","ssMFJK7CPa0", "6 - 12", "2 - 3"),
            InsideExerciseItemStorage("Подъемы штанги лежа грудью на наклонной скамье","xwtaHancCQc", "10 - 15", "3 - 4"),
            InsideExerciseItemStorage("Концентрированные сгибания с гантелей","quKVcoTV8T0", "12 - 15", "3 - 4"),
            InsideExerciseItemStorage("Сгибания рук на верхних ручках кроссовера","DG_qts6PodE", "a", "a"),
            InsideExerciseItemStorage("“Молотки”","xkA900B4yt4", "a", "a"),
            InsideExerciseItemStorage("Подъемы на нижнем блоке","BoxwbEi3w7E", "a", "a"),
            InsideExerciseItemStorage("Жим лежа узким хватом","kbf_MdonwSs", "a", "a"),
            InsideExerciseItemStorage("Французский жим","SS5OO8ekqgI", "a", "a"),
            InsideExerciseItemStorage("Отжимания на брусьях в трицепсовом стиле","MEr06Tdg4LI", "a", "a"),
            InsideExerciseItemStorage("Отжимания спиной к скамье","USmaKkCyVRI", "a", "a"),
            InsideExerciseItemStorage("Отжимания от пола с узкой постановкой рук","cs0taFNpfGA", "a", "a"),
            InsideExerciseItemStorage("Разгибания рук с гантелей из-за головы","ixbV51Cd5es", "a", "a"),
            InsideExerciseItemStorage("Разгибания рук на блоке","DG_qts6PodE&t=3s", "a", "a"),
            InsideExerciseItemStorage("Запястные сжимания","2RbSTLBjg3o", "a", "a"),
            InsideExerciseItemStorage("Перекаты грифа в ладонях","bXfH41mLyUI", "a", "a"),
            InsideExerciseItemStorage("Сгибание кистей обратным хватом","yA5-nkHbbAI", "a", "a")
        ),
        mutableListOf(
            InsideExerciseItemStorage("Становая тяга","duSnLRneftc", "10 - 15", "3 - 4"),
            InsideExerciseItemStorage("Подтягивания","fRcEBlLFYUE", "8 - 12", "2 - 4"),
            InsideExerciseItemStorage("Тяга штанги в наклоне","cB3ztFmAXnU", "10 - 15", "3 - 4"),
            InsideExerciseItemStorage("Тяга штанги к подбородку","Y9x7blBNwJo", "10 - 12", "2 - 4"),
            InsideExerciseItemStorage("Тяга вертикального блока широким хватом","HhZsLulSVrs", "12 - 16", "3 - 4"),
            InsideExerciseItemStorage("Тяга горизонтального блока к поясу","jZDy8b0w9QM", "12 - 15", "3 - 4"),
            InsideExerciseItemStorage("Лодочка","3nYPn53Ag_A", "10 - 12", "3"),
            InsideExerciseItemStorage("Мостик","16YKb7wfpTM", "20 - 30 секунд", "2 - 3"),
            InsideExerciseItemStorage("Тяга верхнего блока за голову","3oGFh9Qodpg", "12 - 15", "3 - 4"),
            InsideExerciseItemStorage("Тяга верхнего блока обратным хватом","bFdsGA2kl-c", "12 - 15", "3 - 4"),
            InsideExerciseItemStorage("Гребной тренажер","6Su4JiWJ1NI", "200 - 600 секунд", "2"),
            InsideExerciseItemStorage("Тяга кроссовера","KMDVvEh2FGE", "15 - 20", "2 - 4"),
            InsideExerciseItemStorage("Тяга нижнего кроссовера","lmq8x-WQROY", "12 - 20", "3 - 4"),
            InsideExerciseItemStorage("Гиперэкстензия","iep-2kTrOAg", "12 - 20", "2 - 4"),
            InsideExerciseItemStorage("Сведение лопаток с грудным эспандером","zyHkx5oU3Ms", "10 - 15", "2 - 3"),
            InsideExerciseItemStorage("Тяга собственного веса при помощи резинового жгута","iXvTA4Q1BNo", "10 - 12", "3 - 4"),
            InsideExerciseItemStorage("Гиперэкстензия на фитболе","NcPF9PUAmag", "10 - 15", "2 - 3"),
        ),
        mutableListOf(
            InsideExerciseItemStorage("Скручивания лежа","F86KLvmRCp4", "18 - 25", "2 - 4"),
            InsideExerciseItemStorage("Ситап","FXU-BzCdgHM", "20", "2 - 3"),
            InsideExerciseItemStorage("Косые скручивания","RkFI_8bbedI", "15 - 20", "2 - 4"),
            InsideExerciseItemStorage("Подъемы прямых ног лежа","apzfDiGTXi4", "12 - 20", "2 - 4"),
            InsideExerciseItemStorage("Планка","tZYlPDbBgYw", "40 - 120 секунд", "2 - 3"),
            InsideExerciseItemStorage("Комбинированные скручивания","kBv1yyQN51E", "15 - 25", "2 - 4"),
        ),
        mutableListOf(
            InsideExerciseItemStorage("Мертвая тяга","pV501RQm864", "10 - 15", "3 - 4"),
            InsideExerciseItemStorage("Приседания со штангой в любой вариации","VGNuRAtOQMs", "10 - 15", "2 - 4"),
            InsideExerciseItemStorage("Жим ногами","39rDFUPME7U", "15 - 22", "3 - 4"),
            InsideExerciseItemStorage("Гиперэкстензия","iep-2kTrOAg", "12 - 20", "2 - 4"),
            InsideExerciseItemStorage("Подъем носков в тренажере сидя","XitPbkHneD4", "15 - 20", "3 - 4"),
            InsideExerciseItemStorage("Разведение ног в стороны на тренажере","W4zfXd9iju8", "12 - 15", "3 - 4"),
            InsideExerciseItemStorage("Сгибание/разгибание ног на тренажере","4xEzsITA4Lc", "15 - 20", "3 - 4"),
            InsideExerciseItemStorage("Райдер","B9spXGNa0kA", "1 - 2 минуты", "2 - 3"),
            InsideExerciseItemStorage("Климбер","K0vzcfgs0io", "2 - 4 минуты", "3 - 4"),
            InsideExerciseItemStorage("Велотренажер","SuafQ4hzSCQ", "15 - 30 минут", "1"),
            InsideExerciseItemStorage("Эллипсоиды","1hAIFIlGggA", "20 - 30 минут", "1"),
            InsideExerciseItemStorage("Воздушные приседания","azJz7HX8uHI", "15 - 20", "2 - 4"),
            InsideExerciseItemStorage("Выпады","d3xVz2ObWyg", "15 - 20", "3 - 4"),
            InsideExerciseItemStorage("Наклоны к прямым ногам","QpapbVPFOjI", "20 секунд тянуться, 10 удерживать", "2 - 4"),
            InsideExerciseItemStorage("Выпрыгивания","mDgH3BLK8YQ", "20 - 25", "2 - 3"),
            InsideExerciseItemStorage("Глубокие выпады без веса","clW8MBH_HAU", "15 - 20", "3 - 4"),
            InsideExerciseItemStorage("Полушпагаты – поперечные и продольные","8rcjFCFO4aY", "1", "2 - 3"),
            InsideExerciseItemStorage("Шпагаты - поперечные и продольные","8S5FmblQV-M", "1", "2"),
            InsideExerciseItemStorage("Махи ногами","r8A2AitNico", "10 - 15", "2 - 3"),
        )

    )
}